config/routes.rb
Rails.application.routes.draw do
  resources :gists
  resources :categories
  devise_for :companies

  root "page#home"
  match "add-gist/" => "gists#add_gists", via:[:get,:post]
  match "search/result/" => "gists#search", via:[:get,:post]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :gists
end

app/models/company.rb
class Company < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :gists
end

app/models/gist.rb
require 'elasticsearch/model'
class Gist < ActiveRecord::Base
  # include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks

  belongs_to :company
  belongs_to :category

  def self.search(search)
    where("user LIKE ? OR name LIKE ? OR gists_id LIKE ? OR category_id LIKE ?", "%#{search}%","%#{search}%","%#{search}%","%#{self.search_category(search)}%")
  end
  def self.search_category(search)
    cat = Category.find_by_name(search)
    return cat.id if !cat.blank?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_devise_permitted_parameters, if: :devise_controller?


  protected
  def configure_devise_permitted_parameters
    registration_params = [:role, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) {
        |u| u.permit(registration_params << :current_password)
    }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) {
        |u| u.permit(registration_params)
      }
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/gists_controller.rb
require "gists/gists_books"
class GistsController < ApplicationController
  include Gists

  before_action :set_gist, only: [:show, :edit, :update, :destroy]
  before_action :company_sign?, only: [:create,:new,:edit, :update, :destroy, :show, :index]

  # GET /gists
  # GET /gists.json
  def index
    @gists = Gist.all
  end

  # GET /gists/1
  # GET /gists/1.json
  def show
  end

  # GET /gists/new
  def new
    @gist = Gist.new
  end

  # GET /gists/1/edit
  def edit
  end

  # POST /gists
  # POST /gists.json
  def create
    @gist = Gist.new(gist_params)

    respond_to do |format|
      if @gist.save
        format.html { redirect_to @gist, notice: 'Gist was successfully created.' }
        format.json { render :show, status: :created, location: @gist }
      else
        format.html { render :new }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_gists
    puts params.inspect
    if params[:login] && params[:pwd]
      user = Gists::GistsBook.new("#{params[:login]}","#{params[:pwd]}")
      if user.get_gists_all
        flash[:error] = ""
        save_gists(user)
      else
        flash[:error] = "Vous n'avez pas de gists"
      end
    end
  end

  # PATCH/PUT /gists/1
  # PATCH/PUT /gists/1.json
  def update
    respond_to do |format|
      if @gist.update(gist_params)
        format.html { redirect_to @gist, notice: 'Gist was successfully updated.' }
        format.json { render :show, status: :ok, location: @gist }
      else
        format.html { render :edit }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gists/1
  # DELETE /gists/1.json
  def destroy
    @gist.destroy
    respond_to do |format|
      format.html { redirect_to gists_url, notice: 'Gist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #search
  def search
     if params[:search]
       @search = Gist.search(params[:search])
     else
       @search = nil
     end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gist
      @gist = Gist.find(params[:id])
    end

    def save_gists(user)
      cpt = 0
      count = user.gists_count
      user.get_gists_all.each do |g|
        @gists = Gist.new
        @gists.user = user.get_user.login
        @gists.avatar = user.get_user.avatar_url
        @gists.name = user.get_name_all_gists[cpt]
        @gists.gists_id = g.id
        @gists.company_id = current_company.id
        cpt = +1
        @gists.save!
        if count == cpt
          redirect_to gists_path
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gist_params
      params.require(:gist).permit(:name, :user, :avatar, :gists_id, :company_id, :category_id)
    end

    def company_sign?
      if !current_company
        redirect_to '/', status: :found, notice: "Vous n'avez pas le droit ou pas access à cette page"
      end
    end

end

app/controllers/page_controller.rb
require "gists/gists_books"
class PageController < ApplicationController
  include Gists
  def home
    if company_signed_in?
      puts "true"
      redirect_to :controller =>"gists", :action =>"add_gists"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Liste des catégories
.panel.panel-default
  .panel-heading Panel heading
  %table.table
    %thead
      %tr
        %th Name
        %th Voir
        %th Edit
        %th Supprimer
    %tbody
      - @categories.each do |category|
        %tr
          %td= category.name
          %td= link_to 'Show', category
          %td= link_to 'Edit', edit_category_path(category)
          %td= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }
= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path

app/views/gists/_form.html.haml
= form_for @gist do |f|
  - if @gist.errors.any?
    #error_explanation
      %h2= "#{pluralize(@gist.errors.count, "error")} prohibited this gist from being saved:"
      %ul
        - @gist.errors.full_messages.each do |msg|
          %li= msg


  .field
    = f.label :category
    = f.select :category_id, Category.all.collect{|n| [n.name, n.id]},{selected: @gist.category_id},{class: 'select_form'}
  .actions
    = f.submit 'Save'

app/views/gists/add_gists.html.haml
.container
  %p
    Veuillez ajouter votre login github et votre mot de passe.
  %form.form-signin{action:"#{add_gist_path}",method:"POST"}
    %input{type:"hidden", name:request_forgery_protection_token.to_s, value: form_authenticity_token }
    .input-group
      %span.input-group-addon.glyphicon.glyphicon-user#basic-addon1
      %input.form-control{placeholder: "name", "aria-describedby"=>"basic-addon1",name:"login"}

    .input-group
      %span.input-group-addon.glyphicon.glyphicon-flash#basic-addon1
      %input.form-control{placeholder: "Password", "aria-describedby"=>"basic-addon1",name:"pwd", type:"password"}
    %button.btn.btn-lg.btn-primary.btn-block{type:"submit"}
      Ajouter vos gists automatiquement

    %p= flash[:error]

app/views/gists/edit.html.haml
%h3 Ajouter une catégorie à votre gist

= render 'form'

= link_to 'Show', @gist
\|
= link_to 'Back', gists_path

app/views/gists/index.html.haml
= render "gists/renders/list_gist", :gist => @gists

app/views/gists/new.html.haml
%h1 New gist

= render 'form'

= link_to 'Back', gists_path

app/views/gists/render/_list_gist.html.haml
-# %h1 Liste des gists
-# .panel.panel-default
-#   .panel-heading Panel heading
-#   %table.table
-#     %thead
-#       %tr
-#         %th #
-#         %th Name
-#         %th User
-#         %th Gists
-#         %th Email Company
-#         %th Category
-#         %th Voir
-#         %th Edit
-#         %th Supprimer
-#     %tbody
-#       - gists.each do |g|
-#         %tr
-#           %td= image_tag(gist.avatar,:alt => "image", :width => 20, :height => 20,)
-#           %td= g.name
-#           %td= g.user
-#           %td= g.gists_id
-#           %td= g.company.email
-#           - if !g.category.nil?
-#             %td= g.category.name
-#           - else
-#             %td pas de catégorie enregistré
-#
-#           %td= link_to 'Show', g
-#           %td= link_to 'Edit', edit_gist_path(g)
-#           %td= link_to 'Destroy', g, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/gists/renders/_list_gist.html.haml
%h1 Liste des gists
.panel.panel-default
  .panel-heading Panel heading
  %table.table
    %thead
      %tr
        %th #
        %th Nom du fichier
        %th Utilisateur
        %th Gists
        %th Email Company
        %th Categorie
        %th Voir
        %th Edit
        %th Supprimer
    %tbody
      - gist.where(company_id: current_company).each do |gist|
        %tr
          %td= image_tag(gist.avatar,:alt => "image", :width => 20, :height => 20)
          %td= gist.name
          %td= gist.user
          %td= gist.gists_id
          %td= gist.company.email
          - if !gist.category.nil?
            %td= gist.category.name
          - else
            %td pas de catégorie enregistré

          %td= link_to 'Show', gist
          %td= link_to 'Edit', edit_gist_path(gist)
          %td= link_to 'Destroy', gist, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/gists/search.html.haml
- if !@search.blank?
  = render "gists/renders/list_gist", :gist => @search
- else
  %h3 Oupss Rien trouvé ;)

app/views/gists/show.html.haml
%p#notice= notice

.panel.panel-default
  .panel-heading
    %h3.panel-title
      = image_tag(@gist.avatar,:alt => "image", :width => 30, :height => 30)
      = @gist.name
  .panel-body
    %p
      %b Auteur:
      = @gist.user
    %p
      %b Gists Id:
      = @gist.gists_id
    %p
      %b Catégorie:
      - if !@gist.category.nil?
        = @gist.category.name
      - else
        Pas de catégorie !
    %p
      %a.btn.btn-primary.btn-lg{href: "https://gist.github.com/#{@gist.gists_id}", role: "button", target:"_blank"}
        = @gist.name

= link_to 'Edit', edit_gist_path(@gist)
\|
= link_to 'Back', gists_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ExoGist
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default.navbar-static-top
      .container.collapse.navbar-collapse
        %ul.nav.navbar-nav
          - if company_signed_in?
            %li
              %a{href:"/"}
                Ajouter des gists
            %li
              %a{href:"#{gists_path}"}
                voir les gists
            %li
              %a{href:"#{categories_path}"}
                Voir les catégories
            %li
              %a{href:"#{new_category_path}"}
                Ajouter de nouvelle catégorie
          %li
            - if company_signed_in?
              =link_to "Déconnection",destroy_company_session_path, method: :delete
            - else
              %a{href:"#{new_company_session_path}"}
                Connexion
    .container
      - if company_signed_in?
        %p Rechercher avec le nom du gist le pseudo ,l'id du gists ou la catégorie
        .search{style: "margin-bottom:30px; width:500px; margin: auto 0;" }
          %form{ action:"#{search_result_path}", method: "POST"}
            %input{type:"hidden", name:request_forgery_protection_token.to_s, value: form_authenticity_token }
            .input{style:"margin-bottom: 20px"}
              %input.form-control{type:"text", name: "search", placeholder:"Recherche"}

            %button.btn.btn-primary.btn-block{type:"submit"}
              Rechercher
        %hr
      = yield

app/views/page/home.html.haml
.container
  .jumbotron
    %h1 Plateforme pour Gists
    %p Une platefome qui réunit les Gists de votre équipe.
    %p Veuillez vous enregistrer si c'est la première fois.
    %p
      %a.btn.btn-primary.btn-lg{href: "#{new_company_registration_path}", role: "button"}
        Inscription